### Get User Profile
GET http://localhost:8081/api/users/cfe12c4a-76b9-4fbf-a5f2-30113fcfc640
Content-Type: application/json


### Create a New User
### ,
POST http://localhost:8081/api/users/register
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "password": "abc@123",
    "firstName": "John",
    "lastName": "Doe"
}

