POST http://localhost:8082/api/activities
Content-Type: application/json

{
    "userId" : "cfe12c4a-76b9-4fbf-a5f2-30113fcfc640",
    "type" : "SWIMMING",
    "duration" : 300,
    "caloriesBurned" : 400,
    "startTime" : "2026-06-15T07:00:00",
    "additionalMetrics" : {
        "distance" : 10.0,
        "averagePace" : 4.5,
        "heartRate" : 150
    }
}